FROM ghcr.io/graalvm/jdk-community:21
LABEL authors="wangminan"
RUN mkdir arktouros-ui
WORKDIR /arktouros-ui
COPY build/arktouros-webapp/config ./config
COPY build/arktouros-webapp/lib ./lib
# RUN ls -l ./lib
COPY build/arktouros-webapp/arktouros-webapp.jar ./arktouros-webapp.jar
# RUN ls -l
EXPOSE 50052
ENV TZ Asia/Shanghai
ENTRYPOINT java -Dfile.encoding=UTF-8 -jar -Dloader.path=lib arktouros-webapp.jar
