spring:
  application:
    name: arktouros-apm
  datasource:
    driver-class-name: org.h2.Driver
    # 一定要持久化，这玩意是用来做apm缓存的 如果用内存型的话要丢数据 仅限测试环境用
    url: jdbc:h2:./db/apm;MODE=MySQL;AUTO_SERVER=TRUE
    username: sa
    password: sa
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  h2:
    console:
      enabled: true

instance:
  active:
    dataReceiver: otelGrpc

receiver:
  grpc:
    port: 50051
