spring:
  application:
    name: arktouros-apm
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/apm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  sql:
    init:
      mode: embedded
      platform: h2
  h2:
    console:
      enabled: true

instance:
  active:
    dataReceiver: otelGrpc
    dataOperation: h2

receiver:
  grpc:
    port: 50051
