spring:
  application:
    name: arktouros-apm
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/apm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: sa
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  h2:
    console:
      enabled: true

instance:
  active:
    dataReceiver: otelGrpc

receiver:
  grpc:
    port: 50051
