spring:
  application:
    name: arktouros-apm
  datasource:
    driver-class-name: org.h2.Driver
    # 一定要持久化，这玩意是用来做apm缓存的 如果用内存型的话要丢数据 仅限测试环境用
    url: jdbc:h2:./db/apm;DB_CLOSE_DELAY=-1;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
  h2:
    console:
      enabled: true
  data:
    elasticsearch:
      repositories:
        enabled:

instance:
  active:
    dataReceiver: otelGrpc
    sinker: elasticsearch # elasticsearch/h2

receiver:
  grpc:
    port: 50051

elasticsearch:
  serverUrl: https://localhost:9200
  apiKey: gkAetb_uR3-ePhhP5saPPw
  caPos: D:/code/arktouros/docs/http_ca.crt # 证书位置
