version: '3.8'

services:
  arktouros-apm-server:
    image: wangminan/arktouros-apm-server:latest
    container_name: arktouros-apm-server
    ports:
      - "50050:50050"
      - "50051:50051"
    volumes:
      - /root/arktouros/config:/arktouros/config
    networks:
      - elastic

networks:
  elastic:
    external: true
