version: '3.8'

services:
  arktouros-apm-server:
    image: wangminan/arktouros-apm-server:latest
    container_name: arktouros-apm-server
    ports:
      - "50050:50050"
      - "50051:50051"
    volumes:
      # 配置文件目录映射进去
      - /root/arktouros/config:/arktouros/config
      # 日志目录映射出来
      - /root/arktouros/logs:/arktouros/logs
    networks:
      - elastic

networks:
  elastic:
    external: true
