instance:
  active:
    cache: LogQueueCache
    receiver: JsonLogFileReceiver
    preHandler: JsonLogPreHandler
    emitter: OtelGrpcEmitter # OtelGrpcEmitter, ArktourosGrpcEmitter 二选一
  number:
    preHandler: 3
    emitter: 3

receiver:
  otlpLogFile:
    logDir: otel_logs

emitter:
  grpc:
    host: 38.147.172.149
#    host: 127.0.0.1
    port: 50051
    keepAlive:
      enabled: true # 是否进行连接检查 置空默认true
      delay: 5 # timeunit seconds
      maxRetryTimes: 3
