instance:
  cache: LogQueueCache
  receiver: OtlpLogFileReceiver
  preHandler: OtlpLogPreHandler
  emitter: GrpcEmitter

receiver:
  otlpLogFile:
    logDir: otel_logs

emitter:
  grpc:
    host: 127.0.0.1
    port: 50051
    keepAlive:
      enabled: false # 是否进行连接检查 置空默认true
      delay: 5 # timeunit seconds
      maxRetryTimes: 3
