version: "3"

networks:
  elastic:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      elastic:
        ipv4_address: 192.168.1.10
    privileged: true
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      elastic:
        ipv4_address: 192.168.1.11
    privileged: true
