name: backend-deploy.yml
on:
  push:
    tags:
      # 只有有tag的时候才触发部署操作
      - 'v*'

jobs:
  build-and-push-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Graal JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          version: '21.0.2'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Build with Maven in native env
        run: |
          rm -rf ./target
          mvn -Dmaven.test.skip=true -Pnative clean package
          cd build
          tar -zxvf arktouros-apm-api-leaves.tar.gz
          cd arktouros-apm-api
          ll
          cd ../../arktouros-apm/arktouros-apm-api/target
          ll

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and push Apm
        id: docker_build_user
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/arktouros-apm-server:latest
