name: backend-deploy.yml
on:
  push:
    tags:
      # 只有有tag的时候才触发部署操作
      - 'v*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Graal JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          version: '21.0.2'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      - name: Build with Maven in native env
        run: |
          rm -rf ./target
          mvn -Dmaven.test.skip=true -Pnative clean package
          cd build
          tar -zxvf arktouros-apm-api-leaves.tar.gz

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and push Apm
        id: docker_build_user
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/arktouros-apm-server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 传输docker-compose到服务器
        run: |
          sshpass -p ${{secrets.REMOTE_PWD}} scp -r -o StrictHostKeyChecking=no arktouros-apm/arktouros-apm-api/src/main/resources/docker-compose.yaml root@${{secrets.REMOTE_IP}}:/root/arktouros

      - name: 传输部署脚本到服务器
        run: |
          sshpass -p ${{secrets.REMOTE_PWD}} scp -r -o StrictHostKeyChecking=no arktouros-apm/arktouros-apm-api/src/main/resources/run.sh root@${{secrets.REMOTE_IP}}:/root/arktouros

      - name: 授权并执行部署脚本
        run: |
          sshpass -p ${{secrets.REMOTE_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_IP}} "chmod +x /root/arktouros/run.sh && /root/arktouros/run.sh"
