name: "native-build-test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  native-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Graal JDK 21
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' section below for all supported versions
          distribution: 'graalvm' # See 'Options' section below for all available distributions
          version: '21.0.2'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'maven'

      # 我对native构建的要求是不报错就行
      - name: Build with Maven with native env
        run: mvn -Dmaven.test.skip=true -T 2C -Pnative clean package
